import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SessionProvider } from "next-auth/react"
import "./globals.css";
import AuthGuard from "@/components/common/AuthGuard";
import { Toaster } from "@/components/ui/toaster";
import { NavBar } from "@/components/common";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <html lang="en">
        <body className={inter.className}>
          <AuthGuard>
            {children}
            <Toaster />
          </AuthGuard>
        </body>
      </html>
    </SessionProvider>
  );
}
